### ISSUE TITLE
JUnit5 library import

### ISSUE THREAD

**Issue by hellonayeon** [Lotte-CUTEam/Movie-Ticket-System#32]
테스트 코드를 작성하면서 JUnit5를 사용했어요!
`org.junit.jupiter:junit-jupiter:5.8.2`

<br>

저는 IntelliJ `File > Project Structure > Global Libraries` 설정해서 사용했는데, 이렇게되면 라이브러리 파일에 JUnit5 가 없어서 Eclipse 환경에서 컴파일 오류가 납니다 !.

Eclipse 환경에서도 JUnit5 추가 해주세요 ! (수업 내용 토대로)

> 이렇게 하면 저희가 개발하는 데는 문제 없겠지만, 나중에 코드 제출해서 강사님 환경에서 실행시킬 때 문제가 있을 수도 있겠다.. 라는 생각이 들었어요.

> 제출 전에는 lib 폴더에 넣어둬야 하는게 맞는거겠죠 ❓

**Comment by jungeu1509** [comment]
@hellonayeon 
https://www.notion.so/jungew1509/junit-6cb64e21b7e14f6b8c2d854d9ec7ab6d
수업시간엔 이렇게 java 프로젝트에 추가해줘서 따로 추가해주는 방법을 모르겠네용

**Comment by hellonayeon** [comment]
그렇담 Eclipse 에서도 수업시간에 했던대로 설정하구,
이 부분에 대해서는 제출 전에 강사님께 여쭤볼게요 ~!
